"""Per-community filter-pattern aggregation.

For each community, count how often each filter appears across the
community's primary member views. Filters used by many views are
"common scopes" the modeling team can set as defaults in the certified
data model (or expose as parameters with sensible defaults).

Grouping key
------------
Each filter has both a raw SQL `expression` and an `english`
translation. The English is generated by a pattern-matching
translator; semantically-equivalent SQL with minor formatting
differences (`X=1` vs `X = 1`) usually produces the same English.
We group by `english` if present, else by `expression`, with light
whitespace normalization. Better grouping (AST fingerprinting) is
possible but out of scope for this phase -- see
`tools.shared.fingerprint` if we want to upgrade later.

What this module produces
-------------------------
Per community, a sorted list of filter records:
  {
      "english":   "Status C = 'ACTIVE'",
      "sql":       "STATUS_C = 'ACTIVE'",    # representative raw SQL
      "kind":      "where",                    # filter origin: where / join_on / having
      "n_views":   9,
      "views":     ["VW_A", "VW_B", ...],     # sorted list
  }
Sorted by view-count descending. The markdown report in Phase 3e-iii
will typically show only filters used by >= 2 views (single-view
filters are noisy; per-view filters live in cohorts.md).
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from typing import Iterable


def _normalize_filter_key(s: str) -> str:
    """Collapse whitespace + strip; used to group near-identical filter strings."""
    return re.sub(r"\s+", " ", s).strip()


def analyze_filter_patterns(
    views: Iterable[dict],
    community_to_primary: dict[int, set[str]],
    min_views: int = 1,
) -> dict[int, list[dict]]:
    """For each community, count filter occurrences across its primary views.

    Parameters
    ----------
    views : iterable of ViewV1 dicts (business views; post infrastructure-filter)
    community_to_primary : map of community_idx -> set of view names whose
        primary community is this one
    min_views : keep only filters that appear in at least this many views.
        Default 1 (return everything; caller can re-filter for reporting).
        Pass 2 to drop single-view filters from the output entirely.

    Returns
    -------
    community_idx -> list of filter records sorted by view-count desc.
    """
    view_by_name: dict[str, dict] = {
        v.get("view_name"): v for v in views if v.get("view_name")
    }

    result: dict[int, list[dict]] = {}
    for community_idx, primary_views in community_to_primary.items():
        # For each (community), group views by normalized filter key.
        # grouped[key] = { "view_set": set, "english": str, "sql": str, "kind": str }
        grouped: dict[str, dict] = defaultdict(
            lambda: {"view_set": set(), "english": "", "sql": "", "kinds": []}
        )

        for view_name in primary_views:
            view = view_by_name.get(view_name)
            if view is None:
                continue
            # Walk all scopes; collect filters from each. Stewards generally
            # care about WHERE/HAVING filters in main + CTEs. Subquery
            # filters can be noisy; include them but the kind label will
            # distinguish.
            for scope in view.get("scopes") or []:
                for f in scope.get("filters") or []:
                    english = _normalize_filter_key(f.get("english") or "")
                    expression = _normalize_filter_key(f.get("expression") or "")
                    kind = f.get("kind") or "where"
                    # Prefer english as the grouping key (more readable
                    # and already normalized by the translator); fall
                    # back to raw expression.
                    key = english if english else expression
                    if not key:
                        continue
                    grouped[key]["view_set"].add(view_name)
                    grouped[key]["kinds"].append(kind)
                    # First view contributes the representative english+sql.
                    if not grouped[key]["english"]:
                        grouped[key]["english"] = f.get("english") or ""
                    if not grouped[key]["sql"]:
                        grouped[key]["sql"] = f.get("expression") or ""

        # Build the per-community record list, applying the min_views filter.
        records: list[dict] = []
        for key, data in grouped.items():
            if len(data["view_set"]) < min_views:
                continue
            # Most-common `kind` becomes the representative; if all are
            # the same that's the answer, otherwise pick by majority.
            kind_counts = Counter(data["kinds"])
            most_common_kind, _ = kind_counts.most_common(1)[0]
            records.append({
                "english": data["english"],
                "sql": data["sql"],
                "kind": most_common_kind,
                "n_views": len(data["view_set"]),
                "views": sorted(data["view_set"]),
            })

        # Sort by view-count descending; ties broken alphabetically for stability.
        records.sort(key=lambda r: (-r["n_views"], r["english"], r["sql"]))
        result[community_idx] = records

    return result


def count_filter_patterns(filters: dict[int, list[dict]], min_views: int = 2) -> int:
    """Total distinct filter patterns across all communities that appear
    in at least `min_views` views.

    Useful for console-output summary. Defaults to min_views=2 since
    single-view filters aren't really "patterns" (they're per-view).
    """
    return sum(
        1
        for records in filters.values()
        for r in records
        if r["n_views"] >= min_views
    )
