-- Finance Report
SELECT e.PAT_ENC_CSN_ID,
       DATEDIFF(DAY, e.HOSP_ADMSN_TIME, e.HOSP_DISCH_TIME) AS los,
       e.TOTAL_CHARGES,
       e.TOTAL_CHARGES / DATEDIFF(DAY, e.HOSP_ADMSN_TIME, e.HOSP_DISCH_TIME) AS charge_per_day,
       CASE
           WHEN DATEDIFF(DAY, e.HOSP_ADMSN_TIME, e.HOSP_DISCH_TIME) <= 2 THEN 'Short'
           WHEN DATEDIFF(DAY, e.HOSP_ADMSN_TIME, e.HOSP_DISCH_TIME) <= 5 THEN 'Medium'
           ELSE 'Long'
       END AS los_category
FROM PAT_ENC_HSP e
WHERE e.HOSP_DISCH_TIME IS NOT NULL
  AND e.ADT_PAT_CLASS_C = 1
